Rerun benchmarks
CertainLach/jrsonnet pull request #157
Opened 2024-04-07 22:53 UTC by CertainLach

Results are scratch, and will be redone, there was an unexpected background noise on benchmarks machine.

2024-04-08 00:29 UTC, JarvisCraft requested changes

2024-04-08 00:29 UTC, JarvisCraft commented on nix/sjsonnet.nix
> +  jdk20,
JDK 21 is an LTS, so it's probably more preferable

2024-04-26 23:49 UTC, CertainLach commented
For some reason, sandboxed go-jsonnet and jsonnet now refuse to load files by absolute path, despite jrsonnet/rsjsonnet/sjsonnet being fine with this setup.

New alternative Rust implementation looks good, I like that it implements proper TCO (Despite my hybrid TCO in https://github.com/CertainLach/jrsonnet/pull/121), I need to borrow stacktrace building idea from it.

Benchmarks are in progress, right now jrsonnet looks a bit faster, but it is mostly due to more builtins implemented in jsonnet, will evaluate rsjsonnet later.

2024-04-27 00:14 UTC, CertainLach commented
Preliminary benchmarking run for rsjsonnet, comparing it to jrsonnet and other implementations (only quick runs are performed, so some implementations are excluded here)
https://gist.github.com/CertainLach/7d0bbd0d0272bdc5091e5071e20327ee

2024-04-27 14:56 UTC, merged