Use clap prerelease instead of git ref
CertainLach/jrsonnet pull request #44
Opened 2021-06-01 14:02 UTC by bruno-delfino1995

When trying to build non-x64 binaries, my first attempt was to leverage the Rust Ecosystem. However, that was impossible because of a git dependency, as noted [here](https://github.com/CertainLach/jrsonnet/issues/35#issuecomment-844436711) by @CertainLach. I managed to build the binaries using cross compilers, but the workflows turned out quite ugly. Instead of committing to this workflow, I chose to change from the git ref to the recent pre-release of clap-rs.

Since using either ref or pre-release gives us the same API stability, I thought you wouldn't consider this to be a problem. Now we can publish the package to crates.io and leverage the Rust Ecosystem for all the non-x64 architectures.

Related-to: #35

2021-06-02 18:47 UTC, CertainLach requested changes
Clap v3.0.0-beta.2 had issues with groups in --help, but seems like jrsonnet doesn't uses it anymore, and it can be merged

However, i am against disabling musl builds for linux, as those are more universal, and have no issues with incompatible versions of gnu libc (This workflow uses latest release of ubuntu, so resulting binary will require glibc >= 2.32, but LTS debian (buster) has glibc 2.19)
Instead musl should be used for release binaries

2021-06-03 19:38 UTC, bruno-delfino1995 commented
I kept both musl and gcc. Despite musl having better compatibility between versions, gcc/gclibc is the more broadly used libc implementation.

2021-06-03 19:49 UTC, CertainLach commented
Musl also doesn't needs to be installed on target machine to use jrsonnet, as it is statically linked

2021-06-03 19:49 UTC, CertainLach commented
Thanks!

2021-06-03 19:50 UTC, merged

2021-06-05 16:59 UTC, CertainLach commented
Clap also has issues with inlined default arguments, i will revert this commit

Probally better to upload latest clap to crates.io with another name, or just ask clap maintainers to create new prerelease)