Separate jrsonnet-evaluator and stdlib implementation
CertainLach/jrsonnet pull request #82
Opened 2022-08-07 21:44 UTC by CertainLach

2022-08-08 14:52 UTC, JarvisCraft requested changes
Basic build-related issue

2022-08-08 14:52 UTC, JarvisCraft commented on tests/src/lib.rs
> +pub fn add(left: usize, right: usize) -> usize {
Remove the dummy `lib.rs` content.

2022-08-08 14:52 UTC, JarvisCraft commented on tests/Cargo.toml
> +
```suggestion
publish = false

```

2022-09-15 11:18 UTC, JarvisCraft requested changes
Everything looks good although there is a number of small fixes and enhancements

2022-09-18 08:13 UTC, CertainLach commented on bindings/jsonnet/src/import.rs
> +/// Caller should pass correct callback function
I'm not sure how to describe this contract
This function will be called by jrsonnet, and it needs to provide correct values, according to the signature, which is documented on `JsonnetImportCallback` type alias

2022-09-18 08:16 UTC, CertainLach commented on bindings/jsonnet/src/native.rs
> +/// `name`, `raw_params` elements should be a \0-terminated strings
I would prefer keeping `\0`

2022-09-18 08:21 UTC, CertainLach commented on crates/jrsonnet-stdlib/src/manifest.rs
> +	Ok(escape_string_json(&str_))
Argument names should be same between jsonnet and jrsonnet, those names are used for named arguments syntax:
```jsonnet
std.escapeStringJson(str_ = "hello, world!")
````

2022-09-18 08:23 UTC, CertainLach commented on crates/jrsonnet-stdlib/src/types.rs
> +
Here I grouped `is_*` functions

2022-09-18 08:26 UTC, CertainLach commented on bindings/jsonnet/src/native.rs
> +		.expect("name is not utf-8")
Lowercase utf-8 is preferred in error messages, i.e:
https://doc.rust-lang.org/stable/src/core/str/error.rs.html#120

2022-09-18 08:43 UTC, CertainLach commented on bindings/jsonnet/src/val_modify.rs
> +/// `val` should be correct pointer to value allocated using this library
I think I should remove `valid`/`correct` from this and other references, because referenced contents implies pointer validity

2022-09-18 19:44 UTC, CertainLach commented on bindings/jsonnet/src/lib.rs
> +	#[cfg(not(any(target_family = "unix", target_family = "windows")))]
Better implementation will be possible in Rust 1.64:
https://github.com/rust-lang/rust/pull/97915

2022-10-06 23:04 UTC, JarvisCraft commented on bindings/jsonnet/src/lib.rs
> +	#[cfg(not(any(target_family = "unix", target_family = "windows")))]
Since 1.64 has been released, consider fixing it

2022-10-07 00:59 UTC, CertainLach commented on bindings/jsonnet/src/lib.rs
> +	#[cfg(not(any(target_family = "unix", target_family = "windows")))]
Well, I still don't know what to do with unparse

2022-10-15 18:35 UTC, CertainLach commented on crates/jrsonnet-evaluator/src/lib.rs
> +	#[allow(clippy::missing_panics_doc)]
`# Panic` docs are propagated to a calling code, which is bad in this case, as the contract violation is happening in `set_import_resolver` call

2022-10-15 18:45 UTC, JarvisCraft approved these changes

2022-10-15 18:53 UTC, closed without merging